"""create proxy alarm table

Revision ID: 020d591a1a6b
Revises: adac3666a7d2
Create Date: 2022-03-20 13:03:03.606346

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '020d591a1a6b'
down_revision = 'adac3666a7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_alarm',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('proxy_id', sa.Integer(), nullable=False),
                    sa.Column('alarm_type', sa.String(length=255), nullable=False),
                    sa.Column('alarm_state', sa.Enum(app.models.AlarmState), nullable=False),
                    sa.Column('state_changed', sa.DateTime(), nullable=False),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxy_alarm')
    # ### end Alembic commands ###
