"""tor bridges

Revision ID: 023f780c4ed1
Revises: b9cf5358b70f
Create Date: 2022-03-30 16:26:36.038298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023f780c4ed1'
down_revision = 'b9cf5358b70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_alarm_bridge_id_bridge'), 'bridge', ['bridge_id'], ['id'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_group_group_name'), ['group_name'])

    with op.batch_alter_table('mirror', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_mirror_url'), ['url'])

    with op.batch_alter_table('origin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_origin_domain_name'), ['domain_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('origin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_origin_domain_name'), type_='unique')

    with op.batch_alter_table('mirror', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mirror_url'), type_='unique')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_group_group_name'), type_='unique')

    with op.batch_alter_table('alarm', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alarm_bridge_id_bridge'), type_='foreignkey')

    # ### end Alembic commands ###
