"""tor bridges conf

Revision ID: 27205b21be60
Revises: 8ab88cfd1e20
Create Date: 2022-03-30 16:55:54.868701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27205b21be60'
down_revision = '8ab88cfd1e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
