"""add bridge nicknames

Revision ID: 5c69fe874e4d
Revises: e1332e4cb910
Create Date: 2022-04-05 15:48:36.552558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c69fe874e4d'
down_revision = 'e1332e4cb910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
