"""tor bridges conf

Revision ID: 8ab88cfd1e20
Revises: 023f780c4ed1
Create Date: 2022-03-30 16:36:41.405994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab88cfd1e20'
down_revision = '023f780c4ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('destroyed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.drop_column('destroyed')
        batch_op.drop_column('updated')
        batch_op.drop_column('added')

    # ### end Alembic commands ###
