"""empty message

Revision ID: b9cf5358b70f
Revises: 020d591a1a6b
Create Date: 2022-03-30 14:46:41.191642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cf5358b70f'
down_revision = '020d591a1a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=60), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('alarm_type', sa.String(length=255), nullable=False),
    sa.Column('alarm_state', sa.Enum('UNKNOWN', 'OK', 'WARNING', 'CRITICAL', name='alarmstate'), nullable=False),
    sa.Column('state_changed', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['origin.id'], ),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proxy_alarm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_alarm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('proxy_id', sa.INTEGER(), nullable=False),
    sa.Column('alarm_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('alarm_state', sa.VARCHAR(length=8), nullable=False),
    sa.Column('state_changed', sa.DATETIME(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('alarm')
    # ### end Alembic commands ###
