"""tor bridges conf

Revision ID: ec5da94ece61
Revises: 27205b21be60
Create Date: 2022-03-30 18:58:18.100642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5da94ece61'
down_revision = '27205b21be60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bridge_conf', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
