"""proxy lifecycle

Revision ID: f31ac849f6b2
Revises: a67a9c2bb538
Create Date: 2022-03-09 20:51:20.061315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31ac849f6b2'
down_revision = 'a67a9c2bb538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('deprecated', sa.DateTime(), nullable=True))
    op.add_column('proxy', sa.Column('destroyed', sa.DateTime(), nullable=True))
    op.drop_column('proxy', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('deleted', sa.DATETIME(), nullable=True))
    op.drop_column('proxy', 'destroyed')
    op.drop_column('proxy', 'deprecated')
    # ### end Alembic commands ###
